# Generated by Django 5.1 on 2024-08-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creation_date',
        ),
    ]
