# Generated by Django 5.1 on 2024-09-05 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='display_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
